[package]
name = "project-skyhawk"
version = "0.1.0"
authors = ["Patrick M. Howard <pmontgomeryhoward@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hawk_engine = { path = "./hawk_engine"}